micronaut:
  application:
    name: number-converter
endpoints:
  beans:
    sensitive: false
  info:
    sensitive: false
  health:
    sensitive: false
    details-visible: ANONYMOUS
  metrics:
    enabled: true
  routes:
    sensitive: false
  loggers:
    enabled: true
    sensitive: false
  env:
    sensitive: false
